// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcSz5wmgL6caDOAG9RATx4phWKBk0fXic',
    appId: '1:338736390335:web:3c09e9d4537270b8b8660a',
    messagingSenderId: '338736390335',
    projectId: 'organizacionapp-a4fb5',
    authDomain: 'organizacionapp-a4fb5.firebaseapp.com',
    storageBucket: 'organizacionapp-a4fb5.firebasestorage.app',
    measurementId: 'G-BMX7K2Q7PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrf3byMumLn5yb_cltRYpD3ndb4dhx2Bc',
    appId: '1:338736390335:android:51a6359c720e4c5eb8660a',
    messagingSenderId: '338736390335',
    projectId: 'organizacionapp-a4fb5',
    storageBucket: 'organizacionapp-a4fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwOygvAocLClNYTuK6WIoUtYsHNS1L_0Q',
    appId: '1:338736390335:ios:b61f5f4ce141ee0ab8660a',
    messagingSenderId: '338736390335',
    projectId: 'organizacionapp-a4fb5',
    storageBucket: 'organizacionapp-a4fb5.firebasestorage.app',
    androidClientId: '338736390335-ttgk8l8fulfnkjjlj3u2ldbejrajfahs.apps.googleusercontent.com',
    iosClientId: '338736390335-kqiisb4l5arue0mif5mi7mo2i0acitvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appOrganizacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwOygvAocLClNYTuK6WIoUtYsHNS1L_0Q',
    appId: '1:338736390335:ios:b61f5f4ce141ee0ab8660a',
    messagingSenderId: '338736390335',
    projectId: 'organizacionapp-a4fb5',
    storageBucket: 'organizacionapp-a4fb5.firebasestorage.app',
    androidClientId: '338736390335-ttgk8l8fulfnkjjlj3u2ldbejrajfahs.apps.googleusercontent.com',
    iosClientId: '338736390335-kqiisb4l5arue0mif5mi7mo2i0acitvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appOrganizacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcSz5wmgL6caDOAG9RATx4phWKBk0fXic',
    appId: '1:338736390335:web:d52687f6537ff9fbb8660a',
    messagingSenderId: '338736390335',
    projectId: 'organizacionapp-a4fb5',
    authDomain: 'organizacionapp-a4fb5.firebaseapp.com',
    storageBucket: 'organizacionapp-a4fb5.firebasestorage.app',
    measurementId: 'G-66SVTRW7V4',
  );
}
